apiVersion: v1
kind: Pod
metadata:
  labels:
    project: practice
    author: Abdulaziz
    run: nginx2
  name: nginx2
  namespace: exam-23
spec:
  containers:
    - image: nginx
      name: nginx2
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
